### ISSUE TITLE
前车速度

### ISSUE THREAD

**Issue by Alreall** [Bunrning-Bear/Cellular-Automaton-for-self-drive#1]
请问在获取周围车辆信息的时候是怎么得到前车的速度的

**Comment by xionghuichen** [comment]
您好，感谢您的关注。这个工作已经完成很久且不再维护。代码结构不复杂，细节的问题可能还得您自己在调试过程中看一下。

**Comment by Alreall** [comment]
好的



---- 回复的原邮件 ----
| 发件人 | Xiong-Hui ***@***.***> |
| 日期 | 2022年03月11日 16:46 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [xionghuichen/cellular-automaton-for-auto-driver] 前车速度 (Issue #1) |

您好，感谢您的关注。这个工作已经完成很久且不再维护。代码结构不复杂，细节的问题可能还得您自己在调试过程中看一下。

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
